# example netlify.toml
[build]
  command = "yarn build"
  publish = "dist"

## Uncomment to use this redirect for Single Page Applications. 
## Not needed for static site generators.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
